services:
  postgres:
    image: postgres:17-alpine
    container_name: south-apollo-web-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: south_apollo
      POSTGRES_PASSWORD: south_apollo
      POSTGRES_DB: south_apollo_web
    ports:
      - "5436:5432"
    volumes:
      - south-apollo-web-db-data:/var/lib/postgresql/data

volumes:
  south-apollo-web-db-data:
