services:
  postgres:
    image: postgres:16-alpine
    container_name: falcon-app-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: falcon
      POSTGRES_PASSWORD: falcon
      POSTGRES_DB: falcon_app
    ports:
      - "5433:5432"
    volumes:
      - falcon-app-db-data:/var/lib/postgresql/data

volumes:
  falcon-app-db-data:
